### ISSUE TITLE
Code reuse rights

### ISSUE THREAD

**Issue by palanik** [nprapps/armslist-scraper#11]
[README](https://github.com/nprapps/armslist-scraper/blob/master/README.md) conflicts with MIT [LICENSE](https://github.com/nprapps/armslist-scraper/blob/master/LICENSE).

```
No part of these materials may be reproduced, modified, stored in a retrieval system, or retransmitted, in any form or by any means, electronic, mechanical or otherwise, without prior written permission from NPR.
```
What's the deal?

**Comment by eads** [comment]
My apologies. That's boilerplate we leave on our readme until we make a release / make a repo public. Fixed now.

**Comment by palanik** [comment]
👍🏽

**Comment by eads** [comment]
Thanks for the heads up!
